
package prjfinal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {
 ArrayList<Propietario> ListaProp;
  ArrayList<Inflaçoes> ListaInfla;
  
  public void carregarTAB(){
      DefaultTableModel Modelo = new DefaultTableModel (new Object[]{"Nome","Cpf","Bloco","Apartamento"},0);
      for(int i=0;i<ListaProp.size();i++){
         Object Linha []= new Object[]{ListaProp.get(i).getNome(),
                                     ListaProp.get(i).getCpf(),
                                     ListaProp.get(i).getBloco(),
                                     ListaProp.get(i).getApt()};
        Modelo.addRow(Linha);
      }
      jTable1.setModel(Modelo);
      jTable1.getColumnModel().getColumn(0).setMinWidth(100);
      jTable1.getColumnModel().getColumn(1).setMinWidth(100);
      jTable1.getColumnModel().getColumn(2).setMinWidth(20);
      jTable1.getColumnModel().getColumn(3).setMinWidth(20);
      carregarBOX();
              }
    public void carregarTABTWO(){
      DefaultTableModel Modelo = new DefaultTableModel (new Object[]{"Nome","Avertencia","Multa","Hora","Valor","Dia"},0);
      for(int i=0;i<ListaInfla.size();i++){
         Object Linha []= new Object[]{ListaInfla.get(i).getNome(),
                                     ListaInfla.get(i).getAdventencia(),
                                     ListaInfla.get(i).getMulta(),
                                     ListaInfla.get(i).getHora(),
                                     ListaInfla.get(i).getValor(),
                                     ListaInfla.get(i).getData()
         };
        Modelo.addRow(Linha);
      }
      Jtabela2.setModel(Modelo);
      Jtabela2.getColumnModel().getColumn(0).setMinWidth(50);
      Jtabela2.getColumnModel().getColumn(1).setMinWidth(120);
      Jtabela2.getColumnModel().getColumn(2).setMinWidth(120);
      Jtabela2.getColumnModel().getColumn(3).setMinWidth(20);
      Jtabela2.getColumnModel().getColumn(4).setMinWidth(50);
      Jtabela2.getColumnModel().getColumn(5).setMinWidth(50);
      carregarBOXTWO();
              }
  
  public void carregarBOX(){
       JcNomesProp.removeAllItems();
       JcNomesProp.addItem("Selecione o nome do Morador");
        for(int i=0;i<ListaProp.size();i++){
        JcNomesProp.addItem(ListaProp.get(i).getNome());
        }
  }
    public void carregarBOXTWO(){
       JcNomeInfla.removeAllItems();
       JcNomeInfla.addItem("Selecione o nome do Morador");
        for(int i=0;i<ListaInfla.size();i++){
        JcNomeInfla.addItem(ListaInfla.get(i).getNome());
        }
  }

    public Principal() {
        
        initComponents();
        setLocationRelativeTo(null);
        ListaProp= new ArrayList();
        ListaInfla= new ArrayList();
        JblSalvarEdiçao.setEnabled(false);
        CampoAdvertencia.setEnabled(false);
        CampoMulta.setEnabled(false);
        CampoValor.setEnabled(false);
        CampoAdvertenciaEditar.setEnabled(false);
        CampoMultaEditar.setEnabled(false);
        CampoValorEditar.setEnabled(false);
        JbSalvarInflaEdi.setEnabled(false);
        CampoNomeEditar.setEnabled(false);
        CampoBlocoEditar.setEnabled(false);
        CampoApartamentoEditar.setEnabled(false);
        CampoCpfEditar.setEnabled(false);
        CampoHoraEditar.setEnabled(false);
        CampoDataEditar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblBloco = new javax.swing.JLabel();
        CampoBloco = new javax.swing.JTextField();
        jblSalvar = new javax.swing.JButton();
        jblCancelar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        CampoCpf = new javax.swing.JTextField();
        lblApartamento = new javax.swing.JLabel();
        CampoApartamento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JbExcluir = new javax.swing.JButton();
        JbEditar = new javax.swing.JButton();
        LblNomeEditar = new javax.swing.JLabel();
        CampoNomeEditar = new javax.swing.JTextField();
        LblCpfEditar = new javax.swing.JLabel();
        LblBlocoEditar = new javax.swing.JLabel();
        LblApartamentoEditar = new javax.swing.JLabel();
        CampoCpfEditar = new javax.swing.JTextField();
        CampoBlocoEditar = new javax.swing.JTextField();
        CampoApartamentoEditar = new javax.swing.JTextField();
        JblSalvarEdiçao = new javax.swing.JButton();
        JbCancelarPropEdi = new javax.swing.JButton();
        JValor = new javax.swing.JPanel();
        JbsAdvertencia = new javax.swing.JRadioButton();
        CampoAdvertencia = new javax.swing.JTextField();
        JbsMulta = new javax.swing.JRadioButton();
        CampoMulta = new javax.swing.JTextField();
        JcNomesProp = new javax.swing.JComboBox<>();
        JbSalvarInfla = new javax.swing.JButton();
        JbCancelarInfla = new javax.swing.JButton();
        JHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoHora = new javax.swing.JTextField();
        CampoValor = new javax.swing.JTextField();
        jLData = new javax.swing.JLabel();
        CampoData = new javax.swing.JTextField();
        JbMultaEditar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtabela2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CampoAdvertenciaEditar = new javax.swing.JTextField();
        CampoMultaEditar = new javax.swing.JTextField();
        CampoHoraEditar = new javax.swing.JTextField();
        CampoDataEditar = new javax.swing.JTextField();
        CampoValorEditar = new javax.swing.JTextField();
        JbSalvarInflaEdi = new javax.swing.JButton();
        JbCancelarEditar = new javax.swing.JButton();
        JbAdvertenciaEditar = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JcNomeInfla = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Inflaçoes e Multas");

        lblBloco.setText("Bloco");

        jblSalvar.setText("Salvar");
        jblSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblSalvarActionPerformed(evt);
            }
        });

        jblCancelar.setText("Cancelar");
        jblCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblCancelarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome: ");

        lblCpf.setText("Cpf:");

        lblApartamento.setText("Arpatamento");

        CampoApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblApartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastrar Morador", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Bloco", "Arpatamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        JbExcluir.setText("Excluir");
        JbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirActionPerformed(evt);
            }
        });

        JbEditar.setText("Editar");
        JbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEditarActionPerformed(evt);
            }
        });

        LblNomeEditar.setText("Nome");

        LblCpfEditar.setText("Cpf");

        LblBlocoEditar.setText("Bloco");

        LblApartamentoEditar.setText("Apartamento");

        JblSalvarEdiçao.setText("Salvar Ediçao");
        JblSalvarEdiçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JblSalvarEdiçaoActionPerformed(evt);
            }
        });

        JbCancelarPropEdi.setText("Cancelar");
        JbCancelarPropEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarPropEdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(JbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(JbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(LblCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CampoCpfEditar))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(LblNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CampoNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LblBlocoEditar)
                                .addGap(18, 18, 18)
                                .addComponent(CampoBlocoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(LblApartamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoApartamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(JblSalvarEdiçao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JbCancelarPropEdi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbEditar)
                    .addComponent(JbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNomeEditar)
                    .addComponent(CampoNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CampoCpfEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBlocoEditar)
                    .addComponent(LblApartamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoBlocoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoApartamentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JblSalvarEdiçao, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JbCancelarPropEdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        jTabbedPane2.addTab("Editar Morador", jPanel2);

        buttonGroup1.add(JbsAdvertencia);
        JbsAdvertencia.setText("Advertencia");
        JbsAdvertencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsAdvertenciaActionPerformed(evt);
            }
        });

        buttonGroup1.add(JbsMulta);
        JbsMulta.setText("Multa");
        JbsMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsMultaActionPerformed(evt);
            }
        });

        JcNomesProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcNomesPropActionPerformed(evt);
            }
        });

        JbSalvarInfla.setText("Salvar");
        JbSalvarInfla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSalvarInflaActionPerformed(evt);
            }
        });

        JbCancelarInfla.setText("Cancelar");
        JbCancelarInfla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarInflaActionPerformed(evt);
            }
        });

        JHora.setText("Hora");

        jLabel2.setText("Valor");

        CampoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoHoraActionPerformed(evt);
            }
        });

        jLData.setText("Data");

        CampoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JValorLayout = new javax.swing.GroupLayout(JValor);
        JValor.setLayout(JValorLayout);
        JValorLayout.setHorizontalGroup(
            JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JValorLayout.createSequentialGroup()
                .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JValorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoMulta, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(JbsMulta)
                            .addComponent(CampoAdvertencia)
                            .addComponent(JbsAdvertencia)))
                    .addGroup(JValorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JValorLayout.createSequentialGroup()
                                .addComponent(JHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoHora)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(CampoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JcNomesProp, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JValorLayout.createSequentialGroup()
                                    .addComponent(JbSalvarInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addComponent(JbCancelarInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JValorLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLData)
                        .addGap(18, 18, 18)
                        .addComponent(CampoData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        JValorLayout.setVerticalGroup(
            JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JValorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JbsAdvertencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JbsMulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JcNomesProp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLData)
                    .addComponent(CampoData, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbSalvarInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbCancelarInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Adicionar Inflaçoes", JValor);

        Jtabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Advertencia", "Multa", "Hora", "Valor", "Dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Jtabela2.getTableHeader().setReorderingAllowed(false);
        Jtabela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtabela2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jtabela2);
        if (Jtabela2.getColumnModel().getColumnCount() > 0) {
            Jtabela2.getColumnModel().getColumn(0).setMinWidth(50);
            Jtabela2.getColumnModel().getColumn(1).setMinWidth(100);
            Jtabela2.getColumnModel().getColumn(2).setMinWidth(100);
            Jtabela2.getColumnModel().getColumn(3).setMinWidth(50);
            Jtabela2.getColumnModel().getColumn(4).setMinWidth(50);
            Jtabela2.getColumnModel().getColumn(5).setMinWidth(50);
        }

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CampoHoraEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoHoraEditarActionPerformed(evt);
            }
        });

        JbSalvarInflaEdi.setText("Salvar Ediçao");
        JbSalvarInflaEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSalvarInflaEdiActionPerformed(evt);
            }
        });

        JbCancelarEditar.setText("Cancelar");
        JbCancelarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarEditarActionPerformed(evt);
            }
        });

        buttonGroup2.add(JbAdvertenciaEditar);
        JbAdvertenciaEditar.setText("Advertencia");
        JbAdvertenciaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAdvertenciaEditarActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Multa");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora");

        jLabel3.setText("Data");

        jLabel4.setText("Valor");

        javax.swing.GroupLayout JbMultaEditarLayout = new javax.swing.GroupLayout(JbMultaEditar);
        JbMultaEditar.setLayout(JbMultaEditarLayout);
        JbMultaEditarLayout.setHorizontalGroup(
            JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                        .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                .addComponent(JbAdvertenciaEditar)
                                .addGap(159, 159, 159)
                                .addComponent(jRadioButton2))
                            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                        .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JbMultaEditarLayout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                                .addComponent(CampoDataEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(186, 186, 186))
                                            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                                .addComponent(CampoHoraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CampoValorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))))
                                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                                        .addComponent(JcNomeInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(186, 186, 186)))
                                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JbSalvarInflaEdi, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(JbCancelarEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                        .addComponent(CampoAdvertenciaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CampoMultaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        JbMultaEditarLayout.setVerticalGroup(
            JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JbMultaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbAdvertenciaEditar)
                    .addComponent(jRadioButton2))
                .addGap(4, 4, 4)
                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoMultaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoAdvertenciaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JbSalvarInflaEdi, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JbCancelarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JbMultaEditarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(JcNomeInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoHoraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoValorEditar)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JbMultaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoDataEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Editar Inflaçoes", JbMultaEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtabela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtabela2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtabela2MouseClicked

    private void CampoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDataActionPerformed

    private void CampoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoHoraActionPerformed

    private void JbSalvarInflaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSalvarInflaActionPerformed
       try{
        int x=  JcNomesProp.getSelectedIndex();
        if(x==0){
          JOptionPane.showConfirmDialog(null,"Campo nao preenchido","alerta",JOptionPane.PLAIN_MESSAGE);
        }
        else{
            Inflaçoes inf = new Inflaçoes();
            inf.setNome(ListaProp.get(x-1).getNome());
            inf.setData(CampoData.getText());
            if(JbsAdvertencia.isSelected()==true){
            inf.setAdventencia(CampoAdvertencia.getText());
             CampoAdvertencia.setText("");
            }
            else{
            inf.setMulta(CampoMulta.getText());  
            CampoMulta.setText("");
            int valor= Integer.parseInt(CampoValor.getText());
            inf.setValor(valor);
            }
           
            inf.setHora(CampoHora.getText());
            inf.setData(CampoData.getText());
            int flag = JOptionPane.showConfirmDialog(null,"Confirmar informaçes da Inflaçao","Corfirma Envio!",NORMAL);
        if(flag==0){
        JOptionPane.showConfirmDialog(null,"Cadastro da Inflaçao feito com sucesso","confirmaçao",JOptionPane.PLAIN_MESSAGE);
            ListaInfla.add(inf);
            carregarTABTWO();
            CampoHora.setText("");
            CampoValor.setText("");
            CampoData.setText("");
        }

        }
       }
       catch(Exception e){
        JOptionPane.showConfirmDialog(null,"Erro no preenchimento dos campos","Alerta",JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_JbSalvarInflaActionPerformed

    private void JblSalvarEdiçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JblSalvarEdiçaoActionPerformed
       try{
        int ap= Integer.parseInt(CampoApartamentoEditar.getText());
        int bc= Integer.parseInt(CampoBlocoEditar.getText());
        Propietario prop= new Propietario ( CampoNomeEditar.getText(),CampoCpfEditar.getText(),ap,bc);
        int x=jTable1.getSelectedRow();
        ListaProp.get(x).setNome(CampoNomeEditar.getText());
        ListaProp.get(x).setCpf(CampoCpfEditar.getText());
        ListaProp.get(x).setBloco(bc);
        ListaProp.get(x).setApt(ap);
        carregarTAB();
        CampoNomeEditar.setText("");
        CampoBlocoEditar.setText("");
        CampoApartamentoEditar.setText("");
        CampoCpfEditar.setText("");
        CampoNomeEditar.setEnabled(false);
        CampoBlocoEditar.setEnabled(false);
        CampoApartamentoEditar.setEnabled(false);
        CampoCpfEditar.setEnabled(false);
    }
       catch(Exception e){
        JOptionPane.showConfirmDialog(null,"Erro no preenchimento dos campos","Alerta",JOptionPane.INFORMATION_MESSAGE); 
       }
    }//GEN-LAST:event_JblSalvarEdiçaoActionPerformed

    private void JbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEditarActionPerformed
        JblSalvarEdiçao.setEnabled(true);
        CampoNomeEditar.setEnabled(true);
        CampoBlocoEditar.setEnabled(true);
        CampoApartamentoEditar.setEnabled(true);
        CampoCpfEditar.setEnabled(true);
    }//GEN-LAST:event_JbEditarActionPerformed

    private void JbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirActionPerformed
        int x=jTable1.getSelectedRow();
        if(x>=0 && x<=ListaProp.size()){
            ListaProp.remove(x);
        }
        carregarTAB();
    }//GEN-LAST:event_JbExcluirActionPerformed

    private void CampoApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApartamentoActionPerformed

    private void jblCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblCancelarActionPerformed
        CampoNome.setText("");
        CampoBloco.setText("");
        CampoApartamento.setText("");
        CampoCpf.setText("");
    }//GEN-LAST:event_jblCancelarActionPerformed

    private void jblSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblSalvarActionPerformed
        try{
        int ap= Integer.parseInt(CampoApartamento.getText());
        int bc= Integer.parseInt(CampoBloco.getText());
        Propietario prop= new Propietario (CampoNome.getText(),CampoCpf.getText(),ap,bc);
        int flag = JOptionPane.showConfirmDialog(null,"Confirmar informaçes de: "+CampoNome.getText(),"Corfirma Envio!",NORMAL);
        if(flag==0){
        JOptionPane.showConfirmDialog(null,"Cadastro feito com sucesso","confirmaçao",JOptionPane.PLAIN_MESSAGE);
        ListaProp.add(prop);
        carregarTAB();
        CampoNome.setText("");
        CampoBloco.setText("");
        CampoApartamento.setText("");
        CampoCpf.setText("");
        }
        }
        catch(Exception e){
         JOptionPane.showConfirmDialog(null,"Erro no preenchimento dos campos","Alerta",JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jblSalvarActionPerformed

    private void JbsAdvertenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsAdvertenciaActionPerformed
        CampoMulta.setEnabled(false);
        CampoValor.setEnabled(false);
        CampoAdvertencia.setEnabled(true);
    }//GEN-LAST:event_JbsAdvertenciaActionPerformed

    private void JbsMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsMultaActionPerformed
         CampoAdvertencia.setEnabled(false);
        CampoMulta.setEnabled(true);
        CampoValor.setEnabled(true);
    }//GEN-LAST:event_JbsMultaActionPerformed

    private void JbAdvertenciaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAdvertenciaEditarActionPerformed
       CampoMultaEditar.setEnabled(false);
       CampoValorEditar.setEnabled(false);
       CampoAdvertenciaEditar.setEnabled(true);
    }//GEN-LAST:event_JbAdvertenciaEditarActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        CampoAdvertenciaEditar.setEnabled(false);
        CampoMultaEditar.setEnabled(true);
        CampoValorEditar.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JbSalvarInflaEdi.setEnabled(true);
    CampoHoraEditar.setEnabled(true);
    CampoDataEditar.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JbSalvarInflaEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSalvarInflaEdiActionPerformed
        try{
        Inflaçoes inf = new Inflaçoes();
        int y=  JcNomeInfla.getSelectedIndex();
        int x=Jtabela2.getSelectedRow();
        if(y==0){
         JOptionPane.showConfirmDialog(null,"Campo nao preenchido","alerta",JOptionPane.PLAIN_MESSAGE);
        }
        else{
            
         if(JbAdvertenciaEditar.isSelected()==true){
            ListaInfla.get(x).setAdventencia(CampoAdvertenciaEditar.getText());
             CampoAdvertenciaEditar.setText("");
            }
            else{
            ListaInfla.get(x).setMulta(CampoMultaEditar.getText());
            CampoMultaEditar.setText("");
            int valor= Integer.parseInt(CampoValorEditar.getText());
            ListaInfla.get(x).setValor(valor);
            }
            
        ListaInfla.get(x).setNome(ListaInfla.get(y-1).getNome());
        ListaInfla.get(x).setHora(CampoHoraEditar.getText());
        ListaInfla.get(x).setData(CampoDataEditar.getText());
        carregarTABTWO();
        CampoHoraEditar.setText("");
        CampoDataEditar.setText("");
        CampoHoraEditar.setEnabled(false);
        CampoDataEditar.setEnabled(false);
         CampoAdvertenciaEditar.setEnabled(false);
        CampoMultaEditar.setEnabled(false);
        CampoValorEditar.setEnabled(false);
        }
        }
        catch(Exception e){
        JOptionPane.showConfirmDialog(null,"Erro no preenchimento dos campos","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JbSalvarInflaEdiActionPerformed

    private void CampoHoraEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoHoraEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoHoraEditarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int x=Jtabela2.getSelectedRow();
        if(x>=0 && x<=ListaInfla.size()){
            ListaInfla.remove(x);
        }
        carregarTABTWO();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JcNomesPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcNomesPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcNomesPropActionPerformed

    private void JbCancelarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarEditarActionPerformed
         if(JbAdvertenciaEditar.isSelected()==true){
             CampoAdvertenciaEditar.setText("");
            }
            else{
            CampoMultaEditar.setText("");
         }
            CampoHoraEditar.setText("");
            CampoDataEditar.setText("");
    }//GEN-LAST:event_JbCancelarEditarActionPerformed

    private void JbCancelarInflaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarInflaActionPerformed
            if(JbsAdvertencia.isSelected()==true){
             CampoAdvertencia.setText("");
            }
            else{
            CampoMulta.setText("");
         }
            CampoHora.setText("");
            CampoData.setText("");
    }//GEN-LAST:event_JbCancelarInflaActionPerformed

    private void JbCancelarPropEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarPropEdiActionPerformed
        CampoNomeEditar.setText("");
        CampoBlocoEditar.setText("");
        CampoApartamentoEditar.setText("");
        CampoCpfEditar.setText("");
    }//GEN-LAST:event_JbCancelarPropEdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoAdvertencia;
    private javax.swing.JTextField CampoAdvertenciaEditar;
    private javax.swing.JTextField CampoApartamento;
    private javax.swing.JTextField CampoApartamentoEditar;
    private javax.swing.JTextField CampoBloco;
    private javax.swing.JTextField CampoBlocoEditar;
    private javax.swing.JTextField CampoCpf;
    private javax.swing.JTextField CampoCpfEditar;
    private javax.swing.JTextField CampoData;
    private javax.swing.JTextField CampoDataEditar;
    private javax.swing.JTextField CampoHora;
    private javax.swing.JTextField CampoHoraEditar;
    private javax.swing.JTextField CampoMulta;
    private javax.swing.JTextField CampoMultaEditar;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNomeEditar;
    private javax.swing.JTextField CampoValor;
    private javax.swing.JTextField CampoValorEditar;
    private javax.swing.JLabel JHora;
    private javax.swing.JPanel JValor;
    private javax.swing.JRadioButton JbAdvertenciaEditar;
    private javax.swing.JButton JbCancelarEditar;
    private javax.swing.JButton JbCancelarInfla;
    private javax.swing.JButton JbCancelarPropEdi;
    private javax.swing.JButton JbEditar;
    private javax.swing.JButton JbExcluir;
    private javax.swing.JPanel JbMultaEditar;
    private javax.swing.JButton JbSalvarInfla;
    private javax.swing.JButton JbSalvarInflaEdi;
    private javax.swing.JButton JblSalvarEdiçao;
    private javax.swing.JRadioButton JbsAdvertencia;
    private javax.swing.JRadioButton JbsMulta;
    private javax.swing.JComboBox<String> JcNomeInfla;
    private javax.swing.JComboBox<String> JcNomesProp;
    private javax.swing.JTable Jtabela2;
    private javax.swing.JLabel LblApartamentoEditar;
    private javax.swing.JLabel LblBlocoEditar;
    private javax.swing.JLabel LblCpfEditar;
    private javax.swing.JLabel LblNomeEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jblCancelar;
    private javax.swing.JButton jblSalvar;
    private javax.swing.JLabel lblApartamento;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
